{
//=========Macro generated from canvas: c4/
//=========  (Wed Nov 29 15:03:46 2017) by ROOT version5.34/36
   TCanvas *c4 = new TCanvas("c4", "",10,31,1080,759);
   c4->Range(125.0766,-2146.003,125.1016,10747.6);
   c4->SetFillColor(0);
   c4->SetBorderMode(0);
   c4->SetBorderSize(2);
   c4->SetLeftMargin(0.1372913);
   c4->SetRightMargin(0.06215214);
   c4->SetTopMargin(0.03410641);
   c4->SetBottomMargin(0.1664393);
   c4->SetFrameBorderMode(0);
   c4->SetFrameBorderMode(0);
   
   TH1F *h_higgs_mass__1 = new TH1F("h_higgs_mass__1","",100,125.08,125.1);
   h_higgs_mass__1->SetBinContent(40,2);
   h_higgs_mass__1->SetBinContent(42,1);
   h_higgs_mass__1->SetBinContent(43,1);
   h_higgs_mass__1->SetBinContent(46,8);
   h_higgs_mass__1->SetBinContent(47,27);
   h_higgs_mass__1->SetBinContent(48,64);
   h_higgs_mass__1->SetBinContent(49,99);
   h_higgs_mass__1->SetBinContent(50,9817);
   h_higgs_mass__1->SetBinContent(51,9790);
   h_higgs_mass__1->SetBinContent(52,92);
   h_higgs_mass__1->SetBinContent(53,56);
   h_higgs_mass__1->SetBinContent(54,26);
   h_higgs_mass__1->SetBinContent(55,7);
   h_higgs_mass__1->SetBinContent(56,1);
   h_higgs_mass__1->SetBinContent(57,2);
   h_higgs_mass__1->SetBinContent(59,3);
   h_higgs_mass__1->SetBinContent(62,2);
   h_higgs_mass__1->SetBinContent(64,1);
   h_higgs_mass__1->SetEntries(19999);
   h_higgs_mass__1->SetDirectory(0);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *text = ptstats->AddText("h_higgs_mass");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 19999  ");
   text = ptstats->AddText("Mean  =  125.1");
   text = ptstats->AddText("RMS   = 8.666e-005");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   h_higgs_mass__1->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(h_higgs_mass__1);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   h_higgs_mass__1->SetLineColor(ci);
   h_higgs_mass__1->GetXaxis()->SetTitle(" Higgs Mass [GeV]");
   h_higgs_mass__1->GetXaxis()->SetLabelFont(42);
   h_higgs_mass__1->GetXaxis()->SetLabelSize(0.035);
   h_higgs_mass__1->GetXaxis()->SetTitleSize(0.035);
   h_higgs_mass__1->GetXaxis()->SetTitleFont(42);
   h_higgs_mass__1->GetYaxis()->SetTitle("               #counts");
   h_higgs_mass__1->GetYaxis()->SetLabelFont(42);
   h_higgs_mass__1->GetYaxis()->SetLabelSize(0.035);
   h_higgs_mass__1->GetYaxis()->SetTitleSize(0.035);
   h_higgs_mass__1->GetYaxis()->SetTitleFont(42);
   h_higgs_mass__1->GetZaxis()->SetLabelFont(42);
   h_higgs_mass__1->GetZaxis()->SetLabelSize(0.035);
   h_higgs_mass__1->GetZaxis()->SetTitleSize(0.035);
   h_higgs_mass__1->GetZaxis()->SetTitleFont(42);
   h_higgs_mass__1->Draw("");
   
   TH1F *h_higgs_mass__2 = new TH1F("h_higgs_mass__2","",100,125.08,125.1);
   h_higgs_mass__2->SetBinContent(32,1);
   h_higgs_mass__2->SetBinContent(35,1);
   h_higgs_mass__2->SetBinContent(36,2);
   h_higgs_mass__2->SetBinContent(37,3);
   h_higgs_mass__2->SetBinContent(39,1);
   h_higgs_mass__2->SetBinContent(40,3);
   h_higgs_mass__2->SetBinContent(41,7);
   h_higgs_mass__2->SetBinContent(42,6);
   h_higgs_mass__2->SetBinContent(43,1);
   h_higgs_mass__2->SetBinContent(44,1);
   h_higgs_mass__2->SetBinContent(45,11);
   h_higgs_mass__2->SetBinContent(46,15);
   h_higgs_mass__2->SetBinContent(47,67);
   h_higgs_mass__2->SetBinContent(48,176);
   h_higgs_mass__2->SetBinContent(49,307);
   h_higgs_mass__2->SetBinContent(50,9444);
   h_higgs_mass__2->SetBinContent(51,9352);
   h_higgs_mass__2->SetBinContent(52,281);
   h_higgs_mass__2->SetBinContent(53,182);
   h_higgs_mass__2->SetBinContent(54,74);
   h_higgs_mass__2->SetBinContent(55,24);
   h_higgs_mass__2->SetBinContent(56,6);
   h_higgs_mass__2->SetBinContent(57,4);
   h_higgs_mass__2->SetBinContent(58,8);
   h_higgs_mass__2->SetBinContent(59,6);
   h_higgs_mass__2->SetBinContent(61,3);
   h_higgs_mass__2->SetBinContent(62,4);
   h_higgs_mass__2->SetBinContent(63,4);
   h_higgs_mass__2->SetBinContent(64,3);
   h_higgs_mass__2->SetBinContent(65,3);
   h_higgs_mass__2->SetEntries(20000);
   h_higgs_mass__2->SetDirectory(0);
   h_higgs_mass__2->SetLineColor(2);
   h_higgs_mass__2->GetXaxis()->SetTitle(" Higgs Mass [GeV]");
   h_higgs_mass__2->GetXaxis()->SetLabelFont(42);
   h_higgs_mass__2->GetXaxis()->SetLabelSize(0.035);
   h_higgs_mass__2->GetXaxis()->SetTitleSize(0.035);
   h_higgs_mass__2->GetXaxis()->SetTitleFont(42);
   h_higgs_mass__2->GetYaxis()->SetTitle("               #counts");
   h_higgs_mass__2->GetYaxis()->SetLabelFont(42);
   h_higgs_mass__2->GetYaxis()->SetLabelSize(0.035);
   h_higgs_mass__2->GetYaxis()->SetTitleSize(0.035);
   h_higgs_mass__2->GetYaxis()->SetTitleFont(42);
   h_higgs_mass__2->GetZaxis()->SetLabelFont(42);
   h_higgs_mass__2->GetZaxis()->SetLabelSize(0.035);
   h_higgs_mass__2->GetZaxis()->SetTitleSize(0.035);
   h_higgs_mass__2->GetZaxis()->SetTitleFont(42);
   h_higgs_mass__2->Draw("same");
   
   TH1F *h_higgs_mass__3 = new TH1F("h_higgs_mass__3","",100,125.08,125.1);
   h_higgs_mass__3->SetBinContent(34,1);
   h_higgs_mass__3->SetBinContent(35,1);
   h_higgs_mass__3->SetBinContent(36,3);
   h_higgs_mass__3->SetBinContent(37,5);
   h_higgs_mass__3->SetBinContent(38,3);
   h_higgs_mass__3->SetBinContent(39,4);
   h_higgs_mass__3->SetBinContent(40,17);
   h_higgs_mass__3->SetBinContent(41,13);
   h_higgs_mass__3->SetBinContent(42,15);
   h_higgs_mass__3->SetBinContent(43,19);
   h_higgs_mass__3->SetBinContent(44,13);
   h_higgs_mass__3->SetBinContent(45,19);
   h_higgs_mass__3->SetBinContent(46,64);
   h_higgs_mass__3->SetBinContent(47,185);
   h_higgs_mass__3->SetBinContent(48,479);
   h_higgs_mass__3->SetBinContent(49,776);
   h_higgs_mass__3->SetBinContent(50,8390);
   h_higgs_mass__3->SetBinContent(51,8343);
   h_higgs_mass__3->SetBinContent(52,791);
   h_higgs_mass__3->SetBinContent(53,504);
   h_higgs_mass__3->SetBinContent(54,184);
   h_higgs_mass__3->SetBinContent(55,57);
   h_higgs_mass__3->SetBinContent(56,17);
   h_higgs_mass__3->SetBinContent(57,14);
   h_higgs_mass__3->SetBinContent(58,13);
   h_higgs_mass__3->SetBinContent(59,17);
   h_higgs_mass__3->SetBinContent(60,16);
   h_higgs_mass__3->SetBinContent(61,16);
   h_higgs_mass__3->SetBinContent(62,11);
   h_higgs_mass__3->SetBinContent(63,4);
   h_higgs_mass__3->SetBinContent(64,2);
   h_higgs_mass__3->SetBinContent(65,2);
   h_higgs_mass__3->SetBinContent(67,2);
   h_higgs_mass__3->SetEntries(20000);
   h_higgs_mass__3->SetDirectory(0);
   h_higgs_mass__3->SetLineColor(3);
   h_higgs_mass__3->GetXaxis()->SetTitle(" Higgs Mass [GeV]");
   h_higgs_mass__3->GetXaxis()->SetLabelFont(42);
   h_higgs_mass__3->GetXaxis()->SetLabelSize(0.035);
   h_higgs_mass__3->GetXaxis()->SetTitleSize(0.035);
   h_higgs_mass__3->GetXaxis()->SetTitleFont(42);
   h_higgs_mass__3->GetYaxis()->SetTitle("               #counts");
   h_higgs_mass__3->GetYaxis()->SetLabelFont(42);
   h_higgs_mass__3->GetYaxis()->SetLabelSize(0.035);
   h_higgs_mass__3->GetYaxis()->SetTitleSize(0.035);
   h_higgs_mass__3->GetYaxis()->SetTitleFont(42);
   h_higgs_mass__3->GetZaxis()->SetLabelFont(42);
   h_higgs_mass__3->GetZaxis()->SetLabelSize(0.035);
   h_higgs_mass__3->GetZaxis()->SetTitleSize(0.035);
   h_higgs_mass__3->GetZaxis()->SetTitleFont(42);
   h_higgs_mass__3->Draw("same");
   
   TLegend *leg = new TLegend(0.6187384,0.4611187,0.9981447,0.6712142,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("h_higgs_mass","blue","lpf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_higgs_mass","h_higgs_mass","lpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_higgs_mass","h_higgs_mass","lpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(3);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   c4->Modified();
   c4->cd();
   c4->SetSelected(c4);
}
